---
# Wordpress configuration
- name: Get url
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: unzip
  unarchive:
    src: /tmp/wordpress.tar.gz
    remote_src: true
    dest: /var/www/html

- name: Copy config-sample.php
  copy:
    src: /var/www/html/wordpress/wp-config-sample.php
    dest: /var/www/html/wordpress/wp-config.php
    remote_src: yes

- name: Put database name in wp-config.php
  replace:
    path: /var/www/html/wordpress/wp-config.php
    regexp: database_name_here
    replace: wordpress

- name: Put username in wp-config.php
  replace:
    path: /var/www/html/wordpress/wp-config.php
    regexp: username_here
    replace: admin

- name: Put password in wp-config.php
  replace:
    path: /var/www/html/wordpress/wp-config.php
    regexp: password_here
    replace: dkagh1.

- name: Put localhost in wp-config.php
  replace:
    path: /var/www/html/wordpress/wp-config.php
    regexp: localhost
    replace: 192.168.56.33
  notify: Restart Apache
