---
# mysql configuration

- name: Re-configure dpkg module before start tasks
  command: sudo dpkg --configure -a

- name: Download MySQL repository
  get_url:
    url: https://dev.mysql.com/get/mysql-apt-config_0.8.12-1_all.deb
    dest: .

- name: Install the repository
  dpkg_selections:
    name: mysql-apt-config_0.8.12-1_all.deb
    selection: install

- name: Update apt pkg list
  apt:
    update_cache: yes

- name: import the missing gpg key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 467B942D3A79BD29

- name: Update apt pkg list
  apt:
    update_cache: yes

- name: Install mysql packages
  apt:
    name: "{{ mysql_pkg_list }}"
    update_cache: yes
    cache_valid_time: 3600
    state: latest

- name: Start and enable mysql service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Set the root password
  mysql_user:
    name: "admin" ##
    password: "{{ mysql_root_password }}"
    host: "localhost"
    priv: "*.*:ALL,GRANT"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Copy .my.cnf file with root password credentials
  template:
    src: ./roles/mysql/files/root_cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: "0600"

- name: Enable remote login to mysql
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "^bind-address"
    line: "bind-address = 0.0.0.0"
    backup: yes
  notify:
    - Restart mysql

- name: Delete anonymous user
  mysql_user:
    user: ""
    host_all: yes
    state: absent
  ignore_errors: yes

- name: Secure the root user for IPv4 localhost
  mysql_user:
    user: admin ##
    password: "{{ mysql_root_password }}"
    host: 127.0.0.1
  no_log: yes
  ignore_errors: yes

- name: Secure the root user for localhost domain
  mysql_user:
    user: admin ##
    password: "{{ mysql_root_password }}"
    host: localhost
  no_log: yes
  tags: db1
  ignore_errors: yes

- name: Remove test databse
  mysql_db:
    name: test
    state: absent
    login_user: admin ##
    login_password: "{{ mysql_root_password }}"
  tags: db1

- name: Create database for Wordpress
  mysql_db:
    name: wordpress
    state: present
    login_user: admin ##
    login_password: "{{ mysql_root_password }}"
  tags: db1

- name: Create user for Wordpress
  mysql_user:
    name: admin
    password: "{{ mysql_user_password }}"
    priv: "wordpress.*:ALL"
    host: "192.168.56.31"
    state: present
    login_user: admin ##
    login_password: "{{ mysql_root_password }}"
  tags: db1

- name: Allow port on mysql
  ufw:
    port: "{{ mysql_port }}"
    proto: tcp
    rule: allow
  tags: db1
