# PHP configuration
---
- name: Add apt repository
    ansible.builtin.apt_repository:
      repo: 'ppa:ondrej/php'

- name: Upgrade and Update apt pkg list
  apt:
    upgrade: 'yes'
    update_cache: yes

- name: Install php
  apt:
    name: "{{ php_list }}"
    state: present
    update_cache: yes
...